name: Deploy (development)

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.GA_USER_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ./dist/widget-admin/browser/* ${{ secrets.GA_USER }}@${{ secrets.WIDGET_HOST }}:${{ secrets.DEPLOY_DIR }}
